# Causes bash to append to history instead of overwriting it so if you start a new terminal, you have old session history
shopt -s histappend
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND ;} history -a"

# Ignore case on auto-completion
bind "set completion-ignore-case on"

# Show auto-completion list automatically, without double tab
bind "set show-all-if-ambiguous On"

# Create and go to the directory
function mkdirg {
	mkdir -p "$1"
	cd "$1"
}

# Aliases put by user
alias cd..='cd ..'
alias cd..='cd ..'
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias rm='trash -v'
alias cat='batcat'
if test -f "/usr/bin/lsd"; then
    alias la='lsd -A --icon never'
    alias ls='lsd --icon never'
    alias ll='lsd -Al --icon never --date "+%-d/%-m %H:%M" --size short --blocks permission,user,group,size,date,name'
else
    alias ls='ls --color=auto'
    alias la='ls -A'
    alias ll='ls -alh'
fi
if test -f "/usr/bin/nala"; then
    alias apt='nala'
fi
alias sudo='sudo '
alias grep='grep --color=auto'
alias shellcheck='shellcheck -x'
alias pc1='ping -c 1 example.com'

# Autojump
if test -f "/usr/share/autojump/autojump.sh"; then
    . /usr/share/autojump/autojump.sh
fi

# Function to use ix.io (the command-line pastebin)
function ix {
    local opts
    local OPTIND
    [ -f "$HOME/.netrc" ] && opts='-n'
    while getopts ":hd:i:n:" x; do
        case $x in
            h) echo "ix [-d ID] [-i ID] [-n N] [opts]"; return;;
            d) $echo curl $opts -X DELETE ix.io/$OPTARG; return;;
            i) opts="$opts -X PUT"; local id="$OPTARG";;
            n) opts="$opts -F read:1=$OPTARG";;
        esac
    done
    shift $(($OPTIND - 1))
    [ -t 0 ] && {
        local filename="$1"
        shift
        [ "$filename" ] && {
            curl $opts -F f:1=@"$filename" $* ix.io/$id
            return
        }
        echo "^C to cancel, ^D to send."
    }
    curl $opts -F f:1='<-' $* ix.io/$id
}

# Variables
DATE=$(date -I)

# Colored Man Pages
export MANPAGER="sh -c 'col -bx | batcat -l man -p'"

# DT's Shell Color Scripts
if test -f "/usr/local/bin/colorscript"; then
    colorscript --random
fi

